### ISSUE TITLE
Structure for various simulator reviews?

### ISSUE THREAD

**Issue by jbae11** [arfc/ddca-litrev#5]
To review various simulators (VISION, ORION, DYMOND..?) and write more efficiently, 
a list of questions should be preset for a more organized, clearer paper.

Questions such as..

- Basic introduction of the simulator?

- Does this simulator have the capacity to predict future demands?

- What is the algorithm it utilizes to do so?

- major drawback / advantage of the simulator?

**Comment by jbae11** [comment]
Can you help me out @katyhuff  @scopatz ?

**Comment by katyhuff** [comment]
@jbae11 -- let's talk about this when we meet Friday. The paper shouldn't be a review of simulators, so there is no need for the basic introduction part (maybe just a sentence or two if needed) and no need for major drawbacks or advantages. The discussion of other simulator capabilities should just categorize simulators together in clusters. Basically there will be a couple of categories (1) no automated deployment at all (2) deployment based on forecasting (3) something else. Though we should mention (1) and (2), and indeed we should probably note which simulators do which, we're actually only interested in talking about (3) the something else.

The main question, also, isn't so much "Does this simulator have the capacity to predict future demands?". It is more pointedly: "Does this simulator deploy facilities in response to demands (current or projected)?"

**Comment by katyhuff** [comment]
I'm going to close this (as it is a question that has been answered) in favor of a new issue regarding my ongoing-but-imminent task to include that simulator review info ( #5 )
